remote_theme: pmarsceill/just-the-docs
repository: odddie/sbom-kb

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
exclude: 
  - README.md